### ISSUE TITLE
You can search "blank" which returns an error

### ISSUE THREAD

**Issue by khai93** [khai93/emotebox#11]

**Comment by vandana1499** [comment]
Please describe .

**Comment by khai93** [comment]
In the component SearchBar, there is no check for blank before search happens, could be fixed through the handleSeach function passed down to it from the home component

**Comment by khai93** [comment]
> 
> 
> Please describe .

In the component SearchBar, there is no check for blank before search happens, could be fixed through the handleSeach function passed down to it from the home component
